{
 "title": "my_dashboard",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PODs Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{container=\"hello-chart\"}) by (pod))/(1024*1024)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PODs CPU usage",
   "type": "gauge",
   "description": "кпу",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"hello-chart-deployment.*\"}[1m])*100) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_request_count_total{}[2m])) by (exported_endpoint)",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "INGRESS RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{}[2m]))",
     "legendFormat": "Total RPS"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, exported_endpoint) (rate(app_request_latency_seconds_bucket[2m])*1000))",
     "legendFormat": "50% {{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, exported_endpoint) (rate(app_request_latency_seconds_bucket[2m])*1000))",
     "legendFormat": "95% {{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, exported_endpoint) (rate(app_request_latency_seconds_bucket[2m])*1000))",
     "legendFormat": "99% {{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum by (le, exported_endpoint) (rate(app_request_latency_seconds_bucket[2m])*1000))",
     "legendFormat": "100% {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "INGRESS Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])*1000))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])*1000))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])*1000))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(1.0, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])*1000))",
     "legendFormat": "100%"
    }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (http_status, exported_endpoint) (rate(app_request_count_total{http_status=~\"4..|5..\"}[2m]))",
     "legendFormat": "{{http_status}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "INGRESS Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status, path) (rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"4..|5..\"}[2m]))",
     "legendFormat": "{{status}} {{path}}"
    }
   ]
  }
 ]
}