replicaCount: 2

image:
  repository: hello-py
#  repository: michaelns/hello-py
  tag: 0.3.0

service:
  type: NodePort
  port: 9000
  targetPort: 80

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  persistence:
    enabled: false
  service:
    port: "5432"
ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths:
        - path: /otusapp/michael(/|$)(.*)
          pathType: Prefix
        - path: /(|$)(.*)
          pathType: Prefix

metrics:
  serviceMonitor:
    enabled: true
